SELECT CNPJ_CIA AS CPNJ, DENOM_CIA as NOME_DA_EMPRESA, DT_FIM_EXERC as DATA_FINAL_DO_EXERCICIO,DS_CONTA AS TIPO_DE_CONTA, VL_CONTA as VALOR_EM_MILHARES_DE_REAIS

FROM finance-459215.CVM_Dataset.BPA_2022

WHERE 
    (DS_CONTA = "Ativo Circulante" OR DS_CONTA = "Ativo Total")
    AND VL_CONTA <> 0 
    AND (DT_FIM_EXERC = "2022-12-31" OR DT_FIM_EXERC = "2021-12-31")
    AND ESCALA_MOEDA = "MIL"